# Generated by Django 5.1.1 on 2024-10-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsdk", "0002_normaluser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100, unique=True)),
                ("totalused", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "公司",
                "db_table": "公司列表",
                "ordering": ["-company"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_num", models.CharField(max_length=100, unique=True)),
                ("order_profile", models.CharField(max_length=100, unique=True)),
                ("max_embed", models.PositiveIntegerField(default=0)),
                ("alreadyused", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="modelsdk.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单表",
                "db_table": "订单表",
                "ordering": ["-order_num"],
            },
        ),
        migrations.CreateModel(
            name="PC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pc_id", models.CharField(max_length=100, unique=True)),
                (
                    "auth_code",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="授权码",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcs",
                        to="modelsdk.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "PC表",
                "db_table": "PC表",
            },
        ),
        migrations.CreateModel(
            name="Embed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embed_id", models.CharField(max_length=100, unique=True)),
                ("id_count", models.PositiveIntegerField(default=0)),
                (
                    "pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeds",
                        to="modelsdk.pc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embed表",
                "db_table": "Embed表",
            },
        ),
    ]
