# Generated by Django 5.1.1 on 2024-10-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelsdk", "0003_company_order_pc_embed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-company"], "verbose_name_plural": "公司"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_num"], "verbose_name_plural": "订单表"},
        ),
    ]
