# Generated by Django 5.1.1 on 2024-10-10 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsdk", "0007_alter_pc_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-created_at"], "verbose_name_plural": "公司"},
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
    ]
