# Generated by Django 5.1.1 on 2024-10-10 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelsdk", "0008_alter_company_options_company_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="embed",
            options={"verbose_name": "Embed"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"], "verbose_name_plural": "订单"},
        ),
        migrations.AlterModelOptions(
            name="pc",
            options={"ordering": ["-created_at"], "verbose_name_plural": "PC"},
        ),
        migrations.AddField(
            model_name="pc",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterModelTable(
            name="embed",
            table="Embed",
        ),
        migrations.AlterModelTable(
            name="order",
            table="订单",
        ),
        migrations.AlterModelTable(
            name="pc",
            table="PC",
        ),
    ]
