# Generated by Django 5.1.2 on 2024-10-15 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdk', '0009_alter_embed_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embed',
            options={'verbose_name_plural': 'Embed'},
        ),
        migrations.AddField(
            model_name='embed',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='modelsdk.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embed',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='modelsdk.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
