# Generated by Django 5.1.2 on 2024-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdk', '0011_company_total_max_alter_embed_id_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'companys'},
        ),
        migrations.AlterModelOptions(
            name='embed',
            options={'verbose_name_plural': 'embed'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'pcs'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='embed',
            name='embed_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='auth_code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='pc_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='embed',
            table='embed',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='pc',
            table='pc',
        ),
    ]
